INSERT INTO tb_users(user_name, user_email, user_password, user_role)
VALUES ("Martim", "martim@gmail.com", "senha@123", "MODERATOR");

INSERT INTO tb_posts(user_id, title, content, moment)
VALUES 
(1, "Meu 1º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", NOW()),
(1, "Meu 2º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 1 HOUR)),
(1, "Meu 3º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 2 HOUR)),
(1, "Meu 4º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 3 HOUR)),
(1, "Meu 5º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 4 HOUR)),
(1, "Meu 6º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 5 HOUR)),
(1, "Meu 7º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 6 HOUR)),
(1, "Meu 8º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 7 HOUR)),
(1, "Meu 9º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 8 HOUR)),
(1, "Meu 10º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 9 HOUR)),
(1, "Meu 11º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 10 HOUR)),
(1, "Meu 12º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 11 HOUR)),
(1, "Meu 13º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 12 HOUR)),
(1, "Meu 14º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 13 HOUR)),
(1, "Meu 15º Post", "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut condimentum quam varius sapien volutpat pretium. Aenean convallis risus vel lectus mollis, eu dictum nulla suscipit. Donec ullamcorper augue eu augue tincidunt, a facilisis lacus suscipit. Vivamus sit amet orci purus. Duis at dignissim metus. Suspendisse in pharetra eros, at varius tellus. Phasellus eu elit eu enim varius blandit vitae et elit. Cras sodales nisi finibus, pellentesque libero in, auctor ipsum. Phasellus eget mi ac augue venenatis rutrum quis vitae tellus.", ADDDATE(NOW(), INTERVAL 14 HOUR));


SELECT * FROM tb_users;
SELECT * FROM tb_posts;



